services:
  rag_service2:
    container_name: rag_service2
    build:
      context: ./rag_service2
      dockerfile: Dockerfile
    working_dir: /app
#    command: uvicorn app.src.main_version.telegrambot:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - /home/user1/sqlite_data_rag/AI_agent.db:/app/src/main_version/AI_agent.db
    ports:
      - "8000:8000"  # Открываем WebSocket на 8000 порту
    environment:
      - GIGACHAT_API_KEY=${GIGACHAT_API_KEY}
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - DATABASE_URI=sqlite:////app/src/main_version/AI_agent.db
    restart: always
    networks:
      - app_network

  monitor2:
    container_name: monitor_service2
    build: ./monitor2
    restart: always
    depends_on:
      - rag_service2
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN} 
      - ALERT_CHAT_ID=${ALERT_CHAT_ID}
      - ALERT_BOT_TOKEN=${ALERT_BOT_TOKEN}   # для monitor
#      - API_URL=http://rag_service2:8000/health
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge