[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:rag_service]
command=/opt/venv_rag/bin/uvicorn app.src.main_version.telegram_bot:app --host 0.0.0.0 --port 8001
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/rag_service.err.log
stdout_logfile=/var/log/supervisor/rag_service.out.log
environment=PYTHONPATH=/app,PATH="/opt/venv_rag/bin:%(ENV_PATH)s"
startretries=5

[program:websocket]
command=/opt/venv_rag/bin/python -m app.src.main_version.websocket_server
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/websocket.err.log
stdout_logfile=/var/log/supervisor/websocket.out.log
environment=PYTHONPATH=/app,PATH="/opt/venv_rag/bin:%(ENV_PATH)s"
startretries=5

[program:admin_panel]
command=/opt/venv_admin/bin/flask run --host=0.0.0.0 --port=5000
directory=/app/admin
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/admin_panel.err.log
stdout_logfile=/var/log/supervisor/admin_panel.out.log
environment=PYTHONPATH=/app,FLASK_APP=app.py,FLASK_ENV=production,PATH="/opt/venv_admin/bin:%(ENV_PATH)s"
startretries=5 