[supervisord]
nodaemon=true
loglevel=info

[program:rag_service]
command=/opt/venv_rag/bin/python -m uvicorn main:app --host 0.0.0.0 --port 8001
directory=/app/src/main_version
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/rag_service_stdout.log
stderr_logfile=/var/log/supervisor/rag_service_stderr.log
environment=PYTHONPATH="/app/src/main_version",TELEGRAM_BOT_TOKEN="%(ENV_TELEGRAM_BOT_TOKEN)s",GIGACHAT_TOKEN="%(ENV_GIGACHAT_TOKEN)s",GIGACHAT_BASE_URL="%(ENV_GIGACHAT_BASE_URL)s",YANDEX_GPT_TOKEN="%(ENV_YANDEX_GPT_TOKEN)s"

[program:websocket]
command=/opt/venv_rag/bin/python websocket_server.py
directory=/app/src/main_version
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/websocket_stdout.log
stderr_logfile=/var/log/supervisor/websocket_stderr.log
environment=PYTHONPATH="/app/src/main_version",TELEGRAM_BOT_TOKEN="%(ENV_TELEGRAM_BOT_TOKEN)s",GIGACHAT_TOKEN="%(ENV_GIGACHAT_TOKEN)s",GIGACHAT_BASE_URL="%(ENV_GIGACHAT_BASE_URL)s",YANDEX_GPT_TOKEN="%(ENV_YANDEX_GPT_TOKEN)s"

[program:admin_panel]
command=/opt/venv_admin/bin/python -m flask run --host=0.0.0.0 --port=5000
directory=/app/admin
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/admin_panel_stdout.log
stderr_logfile=/var/log/supervisor/admin_panel_stderr.log
environment=PYTHONPATH="/app/admin",FLASK_APP="app.py",FLASK_ENV="production",TELEGRAM_BOT_TOKEN="%(ENV_TELEGRAM_BOT_TOKEN)s",GIGACHAT_TOKEN="%(ENV_GIGACHAT_TOKEN)s",GIGACHAT_BASE_URL="%(ENV_GIGACHAT_BASE_URL)s",YANDEX_GPT_TOKEN="%(ENV_YANDEX_GPT_TOKEN)s" 