services:
  rag_service2:
    container_name: rag_service2
    build:
      context: ./rag_service2
      dockerfile: Dockerfile
    working_dir: /app
#    command: uvicorn app.src.main_version.telegram_bot:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - /home/user1/sqlite_data_rag/AI_agent.db:/app/src/main_version/AI_agent.db
    ports:
      - "8001:8001"  # Открываем порт 8001 для FastAPI
      - "8000:8000"  # Открываем WebSocket на 8000 порту
    environment:
      - GIGACHAT_API_KEY=${GIGACHAT_API_KEY}
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - WEBSOCKET_URL=ws://127.0.0.1:8000/ws

    restart: always
    networks:
      - app_network

  monitor2:
    container_name: monitor_service2
    build: ./monitor2
    restart: always
    depends_on:
      - rag_service2
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN} 
      - ALERT_CHAT_ID=${ALERT_CHAT_ID}
      - ALERT_BOT_TOKEN=${ALERT_BOT_TOKEN}   # для monitor
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge